# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe06d2733035641d879d865976afd6c8390646d6cf4a8c89c3b520e25853e82fa0bfb7432e5d944a5c56f2a02a24f4bed7a03952a55da57ab481cf7ae20b6437

test:
  secret_key_base: 1a8a3f6cc17d0d4c8abfafe861aee003cdf6deb9dd3423de1e7c5bb5ae05640207a769fbd1aca0f29253fd68aaf8d0810392f6d98c006c2f18d3cc5ac11d6241

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
